[package]
name = "gif_minecraft"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"  # biblioteka do operacji na obrazach
gif = "0.11"    # biblioteka do odczytywania plików GIF
crossterm = "0.28.1"
ratatui = "0.29.0"


